config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :games do
    resources :ports
  end
  get  "/tools" => "tools#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :title, presence: true
  has_many :ports, :dependent => :destroy
end

app/models/port.rb
class Port < ActiveRecord::Base
  validates :game_id, presence: true
  validates :port_start, presence: true
  validates :port_end, presence: true
  validates :protocol, presence: true
  belongs_to :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  def index
    @games = Game.all
  end

  def show
  end

  def new
    @game = Game.new
  end

  def edit
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      redirect_to games_path, notice: 'Title was added.'
    else
      render :new
    end
  end

  def update
    if @game.update(game_params)
      redirect_to games_path, notice: 'Title was updated.'
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to games_url, notice: 'Game was removed.'
  end
  private

  def set_game
    @game = Game.find(params[:id])
  end

  def game_params
    params.require(:game).permit(:title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ports_controller.rb
class PortsController < ApplicationController
  before_action :set_port, only: [:show, :edit, :update, :destroy]
  before_action :set_game, only: [:new, :create, :edit, :update]

  def index
    @ports = Port.all
  end

  def show
  end

  def new
    @port = Port.new
  end

  def edit
  end

  def create
    @port = Port.new(port_params)

    if @port.save
      redirect_to games_path, notice: 'Port was added.'
    else
      render :new
    end
  end

  def update
    if @port.update(port_params)
      redirect_to games_path, notice: 'Port was updated.'
    else
      render :edit
    end
  end

  def destroy
    @port.destroy
    redirect_to ports_url, notice: 'Port was removed.'
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_port
    @port = Port.find(params[:id])
  end

  def set_game
    @game = Game.find(params[:game_id])
  end

  def port_params
    params.require(:port).permit(:game_id, :port_start, :port_end, :protocol, :system)
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ports_helper.rb
module PortsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this title from being added:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %> <%= f.text_field :title %><br>
  </div>
<BR>
  <div class="actions">
    <%= f.submit 'Submit Game'%>
  </div>
<% end %>

app/views/games/edit.html.erb
<%= render 'shared/header' %>

<h1>Renaming <%= @game.title %></h1>

<%= render 'form' %>
<BR>
<%= link_to 'Back', games_path, class: "btn btn-default btn-xs" %>

<%= render 'shared/donate' %>

app/views/games/index.html.erb
<%= render 'shared/header' %>
<table class="table table-hover table-striped table-condensed">
  <thead>
    <tr>
      <th>Games List</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.title, game %></span></td>
        <br>
        <td><%= link_to 'Rename', edit_game_path(game), class: "btn btn-default btn-xs"  %></td>
        <td><%= link_to 'Delete', game, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add a Game', new_game_path, class: "btn btn-default btn-xs"  %>
<%= render 'shared/donate' %>

app/views/games/new.html.erb
<%= render 'shared/header' %>

<h1>Add a new Game</h1>

<%= render 'form' %>
<BR>
<%= link_to 'Back', games_path, class: "btn btn-default btn-xs" %>

<%= render 'shared/donate' %>

app/views/games/show.html.erb
<%= render 'shared/header' %>
  <h1><strong>Game:</strong> <%= @game.title %></h1>
  <table class="table table-hover table-striped table-condensed">
    <thead>
      <tr>
        <th>Port</th>
        <th>Start</th>
        <th>End</th>
        <th>Protocol</th>
        <th>System</th>
      </tr>
    </thead>
    <tbody>
      <% @game.ports.each do |port| %>
        <tr>
          <td>'Start Port'</td>
          <td>'End Port'</td>
          <td>'Protocol'</td>
          <td>'System'</td>
          <td><%= link_to 'Update', edit_port_path(port), class: "btn btn-default btn-xs"  %></td>
          <td><%= link_to 'Delete', port, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-xs"  %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</p>
  <%= link_to 'Add Port', new_game_port_path(game_id: @game.id), class: "btn btn-default btn-xs" %> |
  <%= link_to 'Rename Title', edit_game_path(@game), class: "btn btn-default btn-xs" %>

app/views/home/index.html.erb
<%= render 'shared/header' %>

<%= render 'shared/donate' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/ports/_form.html.erb
<%= form_for(@port) do |f| %>
  <div class="field">
    <%= f.hidden_field :game_id, value: @game.id %>
    <%= f.label :port_start %> <%= f.number_field :port_start %><br>
    <%= f.label :port_end %> <%= f.number_field :port_end %><br>
    <%= f.select(:protocol, :Protocol => ['TCP', 'UDP', 'Both']) %><br>
    <%= f.select(:system, :System => ['PC', 'PS4', 'Xbox', 'All']) %><br>
  </div>
<BR>
  <div class="actions">
    <%= f.submit 'Add a Port' %>
  </div>
<% end %>

app/views/ports/edit.html.erb
<%= render 'shared/header' %>

<h1>Update <%= @game.title %> Port</h1>

<%= render 'form' %>
<BR>
<%= link_to 'Back', games_path, class: "btn btn-default btn-xs" %>

<%= render 'shared/donate' %>

app/views/ports/new.html.erb
<%= render 'shared/header' %>

<h1>Adding a Port for <%= @game.title %></h1>

<%= render 'form' %>
<BR>
<%= link_to 'Back', games_path, class: "btn btn-default btn-xs" %>

<%= render 'shared/donate' %>

app/views/shared/_donate.html.erb
<BR>
<BR>
Donate to <%= link_to 'Patreon', 'http://www.patreon.com/tythompson', class: "btn btn-default btn-xs"   %>

app/views/shared/_header.html.erb
<h1>Welcome to Ports</h1>
Check out the <%= link_to 'Game List', games_path, class: "btn btn-default btn-xs"   %>
<BR>
Check out the <%= link_to 'Tools', tools_path, class: "btn btn-default btn-xs"   %>
<p id="notice"><%= notice %></p>

app/views/tools/index.html.erb
<h1>Welcome to Ports</h1>
Check out the <%= link_to 'Game List', games_path, class: "btn btn-default btn-xs"   %>
<BR>
Check out the <%= link_to 'Tools', tools_path, class: "btn btn-default btn-xs"   %>